# Generated by Django 4.2.4 on 2023-08-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corredor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombreCompleto', models.CharField(max_length=150)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=16)),
                ('codigoAPS', models.CharField(max_length=4)),
                ('isActive', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
